#!/bin/csh
#set LOAD = (0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9)
set LOAD = (0.096)
#set SA_TYPES = ("rr" "lrs")
set SA_TYPES = ("rr")
#set SA_TYPES = ("V1_RR_P1_RR")
set EXE = ../noc

foreach i ($LOAD)
  foreach s ($SA_TYPES)
    $EXE -load ${i} \
         -topology mesh \
         -mesh:rows 8 -mesh:cols 8 \
         -core_num 64 \
         -bufsz 8 \
         -vc_num 4 \
         -link_width 64 \
         -spec_sa Y \
         -traffic ur \
         -ss_traffic N \
         -warm_cycle 1000 \
         -end_cycle  22000 \
         -progress Y \
         -progress_interval 2000 \
         -outfile "mesh_8x8_ur_load${i}-sa_${s}.out" \
         -sa_type ${s}
  end
end
